name: Publish image to Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/escuelasfamiliares:latest
      - name: publish
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/escuelasfamiliares:latest
