name: Publish image to Docker Hub

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: ['closed']

jobs:
  publish_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/escuelasfamiliares:latest
      - name: publish
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/escuelasfamiliares:latest
      - name: install koyeb
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
      - name: deploy on koyeb
        run: |
          koyeb service update escuelasfamiliares --docker-image ${{ secrets.DOCKERHUB_USERNAME }}/escuelasfamiliares:latest
          koyeb service redeploy escuelasfamiliares
